version: '3'
services:
  # Redis service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # Database service
  db:
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: YtubeSh@re
      MYSQL_DATABASE: ytubeshare

  # Rails API service
  api:
    platform: linux/x86_64
    build:
      context: ./ytubeshare-be
      # dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: mysql2://db:3306/ytubeshare
      REDIS_URL: redis://redis:6379/1
    volumes:
      - ./ytubeshare-be:/app
      

  # ReactJS service
  react:
    build:
      context: ./ytubeshare-fe
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./ytubeshare-fe:/app

  # Nginx proxy service
  proxy:
    build:
      context: ./
    ports:
      - "443:443"

